### ISSUE TITLE
Breakpoint issue

### ISSUE THREAD

**Issue by ronanguilloux** [polypodes/GoogleDrive-based-DMS#3]
"Copy to clipboard" & "download" buttons go underline when resizing viewport to a smaller width screen.

![](https://s3.amazonaws.com/uploads.hipchat.com/133234/964896/gBWGkHcdvkku4uJ/upload.png)

**Comment by nielk** [comment]
fixed

**Comment by ronanguilloux** [comment]
Thnks!
